#!/bin/sh
# wayland autosleep using swayidle
#
# This file is part of Gale.
#
# This is a simple front-end to swayidle that puts the computer to sleep after a
# period of inactivity. It works for any compositor that swayidle supports, ie.
# those that support the idle protocol. $XDG_RUNTIME_DIR and $WAYLAND_DISPLAY
# must both be set.
#
# Dependencies:
#   - swayidle <https://github.com/swaywm/swayidle>
#

echo() { printf '%s\n' "$1"; }
diag() { printf >&2 '%s\n' "$1"; }
quit() { printf >&2 '%s\n' "$2"; exit "$1"; }

usage()
{
  cat <<EOF
usage: wautosleep [<command>]
commands:
     status (default)
  s, start
     autostart
  r, restart
     restart-running
  q, quit
  t, toggle
EOF
}

pidfile()
{
  if [ -z "$XDG_RUNTIME_DIR" ]; then
    quit 1 '$XDG_RUNTIME_DIR is not set!'
  fi
  if [ -z "$WAYLAND_DISPLAY" ]; then
    quit 1 '$WAYLAND_DISPLAY is not set!'
  fi
  pidfile="$XDG_RUNTIME_DIR/wautosleep.$WAYLAND_DISPLAY.pid"
}

_stupid()
{
  stupid --file="$pidfile" "$1" swayidle timeout 600 'systemctl suspend'
}

case $1 in
  status|'')
    pidfile
    _stupid --status
    ;;
  s|start)
    pidfile
    _stupid --start
    ;;
  autostart)
    pidfile
    if [ "$(galconf --get --default=yes wayland.autosleep)" = yes ]; then
      _stupid --start
    fi
    ;;
  r|restart)
    pidfile
    _stupid --restart
    ;;
  restart-running)
    pidfile
    _stupid --restart-running
    ;;
  q|quit)
    pidfile
    _stupid --quit
    ;;
  t|toggle)
    pidfile
    _stupid --toggle
    ;;
  *)
    usage
    exit 1
    ;;
esac
