#!/bin/sh
# gale-sway - sway wrapper

set -eu

# chdir to home directory
cd "$HOME" || exit 2

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

sway-output-mode --noreload
exec sway "$@"
