#!/bin/sh
# sway wrapper
#
# [This file is part of Gale.]
#

echo() { printf '%s\n' "$1"; }
diag() { printf >&2 '%s\n' "$1"; }

# chdir to home directory
cd ~ || exit

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=gtk3
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

sway-output-mode --noreload
exec sway "$@"
