#!/bin/sh

if sel=$(swaymsg -t get_tree \
  | jq -r '
    [.nodes[] | .nodes[]] | sort_by(.name) | .[]
    | .name as $workspace
    | until((.type == "con" or .type == "floating_con")
      and (.nodes | length == 0)
      and (.floating_nodes | length == 0);
      .nodes[], .floating_nodes[])
    | "\(.id):[\($workspace)] \(.name)"' \
  | fzf -d : --with-nth '2..')
then
  echo "${sel%%:*}"
fi
