#
# Alacritty configuration file
#
# This file is part of Gale.
#
# Alacritty is a fast, cross-platform, OpenGL terminal emulator.
#
# Documentation:
#   - alacritty(1)
#   - alacritty(5)
#   - https://github.com/alacritty/alacritty
#

[window]
opacity = 0.8
padding.x = 10
padding.y = 10

[font]
size = 10

[font.normal]

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[colors.selection]
foreground = "#ffffff"
background = "#002a3b"

[colors.bright]
black = "#444444"
red = "#ff2740"
green = "#abe15b"
yellow = "#ffd242"
blue = "#0092ff"
magenta = "#9a5feb"
cyan = "#67fff0"
white = "#ffffff"

[colors.normal]
black = "#232323"
red = "#ff000f"
green = "#8ce10b"
yellow = "#ffb900"
blue = "#008df8"
magenta = "#6d43a6"
cyan = "#00d8eb"
white = "#ffffff"
