#!/bin/sh
# Labwc initialization script
# See labwc-config(5)

hostname=$(uname -n)
if command -v swaybg &> /dev/null && [ -e ~/.gale/wallpaper ]; then
  swaybg -i ~/.gale/wallpaper &
fi
kanshi &
if [ "$hostname" != arcane ]; then
  gale-autosleep &
fi
waybar &
