#!/bin/sh
# Labwc initialization script
# See labwc-config(5)

hostname=$(uname -n)
if command -v swaybg &> /dev/null && [ -e ~/.gale/wallpaper ]; then
  swaybg -i ~/.gale/wallpaper &
fi
kanshi &
if [ "$hostname" != arcane ]; then
  gale-autosleep &
fi
if [ ! -e "$XDG_RUNTIME_DIR/pipewire-0" ]; then
  pipewire &
  sleep 0.1
fi
waybar &
