#!/bin/sh
# bootstrap Gale
#
# This should be run without arguments for interactive first-time installation
# only. If you change the source root, supply the --symlink option, which
# instructs the script to only create the symlink.
#

err() { printf >&2 'error: %s\n' "$1"; }
warn() { printf >&2 'warning: %s\n' "$1"; }
echo() { printf '%s\n' "$1"; }

symlink=

for opt; do
  case "$opt" in
    --symlink) symlink=1 ;;
    *)
      err "invalid option: $opt"
      exit 1
      ;;
  esac
done

# Only environment variables absolutely necessary for installing Gale should
# be declared here.
export EDITOR=vim
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.data"
export XDG_STATE_HOME="$HOME/.state"
export XDG_CACHE_HOME="$HOME/.cache"

lib/sym "$(realpath .)" ~/.local/gale || exit 1

# quit now if --symlink was passed
[ "$symlink" ] && exit 0

# Since executables will not necessarily be installed at ~/.local/bin, we add
# the 'bin' directory to $PATH.
export PATH="$HOME/.local/gale/bin:$PATH"

echo 'Environment ready. Spawning a shell...'
exec "${SHELL:-/bin/sh}"
