#!/bin/sh
# bootstrap - create the ~/.gale symlink

echo() { printf '%s\n' "$1"; }
diag() { printf >&2 '%s\n' "$1"; }
warn() { printf >&2 'warning: %s\n' "$1"; }
err() { printf >&2 'error: %s\n' "$1"; }

if [ "$#" -gt 0 ]; then
  diag 'usage: ./bootstrap'
  exit 1
fi

# compute the relative path from $HOME to cwd
# this will be the contents of the symlink
target=$(realpath --relative-to="$HOME" .) || exit

if real_target=$(readlink ~/.gale 2>/dev/null); then
  if [ "$real_target" != "$target" ]; then
    diag "fixing symlink: $HOME/.gale -> $target"
    ln -sf -T "$target" ~/.gale
  else
    diag "~/.gale symlink OK"
  fi
elif [ -e ~/.gale ]; then
  err "$HOME/.gale exists"
  exit 1
else
  diag "creating symlink: $HOME/.gale -> $target"
  ln -s -T "$target" ~/.gale
fi
