#!/bin/sh
# Gale setup script

set -u

echo() { printf '%s\n' "$*"; }
msg() { printf >&2 '%s\n' "$*"; }
warn() { printf >&2 'warning: %s\n' "$*"; }
err() { printf >&2 'error: %s\n' "$*"; }

if [ $# -ne 1 ]; then
  msg 'usage: ./galsetup <profile>'
  exit 1
fi

profile=$1

# create ~/.gale symlink
link_path="$HOME/.gale"
link_target=$(pwd)
link_target="${link_target#$HOME/}"
echo "Creating symlink: $link_path -> $link_target"
ln -sfT "$link_target" "$link_path"

# set profile
echo "Setting profile to '$profile'"
mkdir -p ~/.config/gale
echo "$profile" > ~/.config/gale/profile
