#!/bin/sh
# gale-sway - sway wrapper
#
# This file is part of Gale.
#

if [ $# -gt 0 ]; then
  echo >&2 'usage: gale-sway'
  exit 1
fi

cd

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export SDL_VIDEODRIVER=wayland

gale-sway-outputs --noreload 1
exec sway
