#!/bin/sh
# gale-labwc-waybar
#
# This file is part of Gale.
#

set -u

echo() { printf '%s\n' "$*"; }
msg() { printf >&2 '%s\n' "$*"; }
warn() { printf >&2 'warning: %s\n' "$*"; }
err() { printf >&2 'error: %s\n' "$*"; }

usage() {
  cat <<EOF
usage: gale-labwc-waybar [status|start|restart|stop]
EOF
}

if [ -z "${WAYLAND_DISPLAY-}" ]; then
  err '$WAYLAND_DISPLAY is not set!'
  exit 1
fi

wrapper() {
  gale-pid "labwc-waybar.$WAYLAND_DISPLAY" "$@"
}

op=${1-status}

case $op in
  status|start|restart|stop)
    wrapper "$op" waybar -c ~/gale/labwc/waybar.jsonc -s ~/gale/labwc/waybar.css
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
