#!/bin/sh
# labwc-waybar
#
# ::::| ~/.config/gale-svc/labwc-waybar
# ::::| ~/.local/bin/gale-labwc-waybar
#

# workaround for wlr/taskbar because waybar 0.12.0 doesn't use
# $XDG_DATA_HOME but does respect $XDG_DATA_DIRS
export XDG_DATA_DIRS="$XDG_DATA_HOME:${XDG_DATA_DIRS:-/usr/share:/usr/local/share}"
exec waybar -c ~/.config/labwc/waybar.jsonc -s ~/.config/labwc/waybar.css "$@"
