" ~/.vimrc - config for vim(1)

" detect if vim-plug is installed
silent! if plug#begin()
  " install plugins
  Plug 'sainnhe/sonokai'
  Plug 'preservim/nerdtree'
  "Plug 'fcpg/vim-altscreen'
  call plug#end()

  let g:sonokai_disable_italic_comment = 1
  let g:sonokai_better_performance = 1

  " apply custom colorscheme
  silent! colorscheme sonokai
endif

let g:NERDTreeShowHidden = 1
let g:NERDTreeDirArrowExpandable = "+"
let g:NERDTreeDirArrowCollapsible = "-"
let g:NERDTreeCascadeSingleChildDir = 0

"
" OPTIONS
"

" backspace over everything
set backspace=indent,eol,start
" indentation
set et sw=2 sts=2 sta ai si
" search
set ic is
" vertical split to the right
set splitright
" single space between joins
set nojoinspaces
" scroll
set scrolloff=5 sidescroll=5 sidescrolloff=5
" display
set number showcmd nowrap title
" automatically insert comment string (ro)
" correct comment join (j)
set formatoptions+=roj
" enable the mouse
set mouse=a

" m   disable menu bar
" M   don't source menu.vim
" t   disable tearoff menu items
" T   disable toolbar
" l/L disable left scrollbar (in split windows)
" r/R disable right scrollbar (in split windows)
set go-=m go-=M go-=t go-=T go-=l go-=L go-=r go-=R

"
" KEYBINDINGS
"

" git shortcuts
nnoremap gis :!git status -sb<CR>
nnoremap gil :!git log<CR>
nnoremap gia :!git add<Space>

" valt bindings in command line
"
"   These mappings are based on vim keybindings with the Alt key pressed.
"   <Esc>-prefix and <M-> mappings are both provided for both the terminal and
"   GUI. To avoid the delay and/or potential conflicts, use <C-C> instead of
"   <Esc> to abort command-line mode.
"
cnoremap <Esc>i <Home>
cnoremap <M-i>  <Home>
cnoremap <Esc>a <End>
cnoremap <M-a>  <End>
cnoremap <Esc>h <Left>
cnoremap <M-h>  <Left>
cnoremap <Esc>l <Right>
cnoremap <M-l>  <Right>
cnoremap <Esc>b <S-Left>
cnoremap <M-b>  <S-Left>
cnoremap <Esc>w <S-Right>
cnoremap <M-w>  <S-Right>
cnoremap <Esc>j <PageDown>
cnoremap <M-j>  <PageDown>
cnoremap <Esc>k <PageUp>
cnoremap <M-k>  <PageUp>
cnoremap <Esc>x <Del>
cnoremap <M-x>  <Del>

" indent faster
nnoremap < <<
nnoremap > >>
vnoremap < <gv
vnoremap > >gv

nnoremap <C-T> :NERDTreeToggle<CR>

"
" MISCELLANEOUS
"

" offer transparent background on terminal emulators
hi Normal       ctermbg=NONE
hi EndOfBuffer  ctermbg=NONE
hi Terminal     ctermbg=NONE ctermfg=NONE
hi LineNr       ctermbg=233 guibg=#222226

" color trailing whitespace red, since trailing space is death
hi TrailSpace ctermbg=1 guibg=#ff0000
match TrailSpace /\s\+$/
au WinNew * match TrailSpace /\s\+$/

if $TERM == "linux"
  hi Visual cterm=reverse
endif

au FileType sh setlocal tw=80 fo-=t
au FileType markdown setlocal tw=80
au FileType make setlocal noet
au BufRead README* setlocal tw=80

" vim:ft=vim
