#
# Fuzzel configuration file
#

font=Oxanium:weight=semibold
anchor=bottom-left
x-margin=10
y-margin=10
horizontal-pad=16

[border]
radius=0

[colors]
border=303036ff
background=000000ff
text=999999ff
match=c080ffff
selection=303036ff
selection-text=ffffffff
selection-match=c080ffff
