# ~/.bash_profile
#
# This file is part of Gale.

# setup the environment
. ~/.profile

systemctl import-environment >/dev/null 2>&1 \
  PATH \
  EDITOR \
  XDG_CONFIG_HOME \
  XDG_DATA_HOME \
  XDG_STATE_HOME \
  XDG_CACHE_HOME

# quit unless interactive
[[ $- != *i* ]] && return

# dialogmenu
#
#   A login menu using dialog(1).
#
dialogmenu() {
  local resp

  while resp="$(dialog --menu Menu 0 0 0 \
    c 'return to command line' \
    q 'logout' \
    s 'sleep' \
    o 'shutdown' \
    r 'reboot' \
    x 'launch X' \
    3>&1 1>&2 2>&3 3>&-
  )"; do  # ^
          # swap stdout and stderr

    case "$resp" in
      q)
        clear
        exit
        ;;
      s)
        systemctl suspend
        ;;
      o)
        clear
        poweroff
        break
        ;;
      r)
        clear
        reboot
        break
        ;;
      x)
        clear
        launchx bspwm
        ;;
      *)
        clear
        break
        ;;
    esac
  done
}

# source local configuration from $XDG_CONFIG_HOME/gale/bash_profile
GALE_LOCAL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/gale/bash_profile"
[[ -s $GALE_LOCAL_CONFIG ]] && . "$GALE_LOCAL_CONFIG"

# CTRL-O opens dialogmenu
bind -m emacs -x '"\C-o":dialogmenu'
bind -m vi-command -x '"\C-o":dialogmenu'
bind -m vi-insert -x '"\C-o":dialogmenu'

# load ~/.bashrc
. ~/.bashrc

# vim:ft=bash
