#!/bin/sh
# ::::| ~/.local/bin/gale-sleep

set -ue

if [ $# -gt 0 ]; then
  echo >&2 "usage: gale-sleep"
  exit 1
fi

if command -v systemctl >/dev/null 2>&1; then
  exec systemctl --no-ask-password suspend
elif command -v loginctl >/dev/null 2>&1; then
  exec loginctl --no-ask-password suspend
elif command -v zzz >/dev/null 2>&1; then
  exec sudo -n zzz
else
  echo >&2 "error: unable to determine sleep method"
  exit 1
fi
