#!/bin/sh
# gale-shutdown - shutdown the system
#
# This file is part of Gale.
#

set -u

echo() { printf '%s\n' "$1"; }
diag() { printf >&2 '%s\n' "$1"; }
warn() { printf >&2 'warning: %s\n' "$1"; }
err() { printf >&2 'error: %s\n' "$1"; }

if [ $# -gt 0 ]; then
  diag "usage: gale-shutdown"
  exit 1
fi

exec poweroff
