#!/bin/sh
# gale-sleep - put the system to sleep
#
# This file is part of Gale.
#
# This script puts the system to sleep using the method specified in the galconf
# variable `sleep-method`. These methods are available:
#
#   systemctl       systemctl suspend (systemd, default)
#   loginctl        loginctl suspend (elogind)
#   zzz             zzz (Void Linux)
#   sudo-*          use sudo
#

set -u

echo() { printf '%s\n' "$1"; }
diag() { printf >&2 '%s\n' "$1"; }
warn() { printf >&2 'warning: %s\n' "$1"; }
err() { printf >&2 'error: %s\n' "$1"; }

if [ $# -gt 0 ]; then
  diag "usage: gale-sleep"
  exit 1
fi

sudo=
method=$(galconf get --default=systemctl sleep-method) || exit 127

case $method in
  sudo-*)
    sudo=sudo
    method=${method#sudo-}
    ;;
esac

case $method in
  systemctl)
    exec systemctl suspend
    ;;
  loginctl)
    exec loginctl suspend
    ;;
  zzz)
    exec zzz
    ;;
  *)
    err "invalid sleep method '$method'"
    exit 127
    ;;
esac
