#!/bin/sh
# gale-reboot - reboot the system
#
# ::::| ~/.local/bin/gale-reboot
#

set -ue

if [ $# -gt 0 ]; then
  echo >&2 "usage: gale-reboot"
  exit 1
fi

if command -v systemctl >/dev/null 2>&1; then
  exec systemctl --no-ask-password reboot
elif command -v loginctl >/dev/null 2>&1; then
  exec loginctl --no-ask-password reboot
else
  exec sudo -n reboot
fi
