#!/bin/sh
# ---
# ~/.local/bin/gale-explorer
# ---

if [ $# -ne 0 ]; then
  echo >&2 "usage: ${0##*/}"
  exit 2
fi

if command -v lf > /dev/null 2>&1; then
  exec gale-term -i gale-explorer -t lf lf
fi

if command -v nautilus > /dev/null 2>&1; then
  exec nautilus
fi

echo >&2 "error: could not find viable file explorer"
exit 127
