#!/bin/sh
# gale-power - shutdown, reboot, suspend, or hibernate
#
# ::::| ~/.local/bin/gale-shutdown
# ::::| ~/.local/bin/gale-reboot
# ::::| ~/.local/bin/gale-sleep
# ::::| ~/.local/bin/gale-hibernate
#

set -ue

progname=${0##*/}

if [ $# -eq 0 ]; then
  operation=${progname#gale-}
else
  operation=$1
fi

has_command() {
  command -v "$1" > /dev/null 2>&1
}

case $operation in
  shutdown)
    if has_command systemctl; then
      exec systemctl --no-ask-password poweroff
    elif has_command loginctl; then
      exec loginctl --no-ask-password poweroff
    else
      exec sudo -n poweroff
    fi
    ;;
  reboot)
    if has_command systemctl; then
      exec systemctl --no-ask-password reboot
    elif has_command loginctl; then
      exec loginctl --no-ask-password reboot
    else
      exec sudo -n reboot
    fi
    ;;
  sleep)
    if has_command systemctl; then
      exec systemctl --no-ask-password suspend
    elif has_command loginctl; then
      exec loginctl --no-ask-password suspend
    elif has_command zzz; then
      exec sudo -n zzz
    else
      echo mem > /sys/power/state
      exit
    fi
    ;;
  hibernate)
    if has_command systemctl; then
      exec systemctl --no-ask-password hibernate
    elif has_command loginctl; then
      exec loginctl --no-ask-password hibernate
    elif has_command ZZZ; then
      exec sudo -n ZZZ
    else
      echo disk > /sys/power/state
      exit
    fi
    ;;
  *)
    echo >&2 "$progname: invalid operation '$operation'"
    exit 2
    ;;
esac
