#!/bin/sh
# gale-shutdown - shutdown the system
#
# ::::| ~/.local/bin/gale-shutdown
#

set -ue

if [ $# -gt 0 ]; then
  echo >&2 "usage: gale-shutdown"
  exit 1
fi

if command -v systemctl >/dev/null 2>&1; then
  exec systemctl --no-ask-password poweroff
elif command -v loginctl >/dev/null 2>&1; then
  exec loginctl --no-ask-password poweroff
else
  exec sudo -n poweroff
fi
