#!/bin/sh
# ---
# ~/.local/bin/gallade
# ---

set -ue
bin=~/.data/gale/gallade
if [ ! -e "$bin" ] ||
   [ "$0" -nt "$bin" ] ||
   [ ~/.gale/gallade.c -nt "$bin" ]; then
  echo >&2 'Compiling...'
  mkdir -p ~/.data/gale
  gcc -std=c99 -Wall -O2 -o "$bin" ~/.gale/gallade.c
fi
exec "$bin" "$@"
