#!/bin/sh
# term - start a terminal
#
# This file is part of Gale.
#

echo() { printf '%s\n' "$1"; }
diag() { printf >&2 '%s\n' "$1"; }
warn() { printf >&2 'warning: %s\n' "$1"; }
err() { printf >&2 'error: %s\n' "$1"; }

usage() {
  cat <<EOF
usage: term [<command> [<args>...]]

Start a terminal.
EOF
}

while [ $# -gt 0 ]; do
  case $1 in
    --)
      shift
      break
      ;;
    -*)
      usage >&2
      exit 1
      ;;
    *)
      break
      ;;
  esac
  shift
done

is_wayland() {
  [ -n "$WAYLAND_DISPLAY" ]
}

has_command() {
  command -v "$1" >/dev/null
}

# alacritty
if has_command alacritty; then
  exec alacritty ${1+-e} "$@"
fi

# foot
if is_wayland && has_command foot; then
  exec foot -- "$@"
fi

# urxvt
if has_command urxvt; then
  exec urxvt ${1+-e} "$@"
fi

# not found
err "could not find viable terminal"
exit 127
