#!/bin/sh
# apply changes

set -e
cd ~/.local/corecon

sym() { ~/.local/corecon/lib/sym "$@"; }

datadir="${XDG_DATA_HOME:-$HOME/.local/share}/corecon"

# symlink dotfiles
for df in bash_profile bashrc dialogrc inputrc screenrc vimrc; do
  sym ~/.local/corecon/"$df" ~/."$df"
done

# symlink executables
for bin in bin/*; do
  name="$(basename "$bin")"
  sym ~/.local/corecon/"$bin" ~/.local/bin/"$name"
done

# SYSTEMD
if corecon config --test systemd; then
  # We don't use $XDG_CONFIG_HOME because when systemd looks for environment.d(5)
  # $XDG_CONFIG_HOME won't be set up yet. So we put it in ~/.config where systemd
  # can find it.
  sym ~/.local/corecon/environment ~/.config/environment.d/corecon.conf
fi

# bootstrap ninja if necessary
if [ ! -e "$datadir/apply.ninja" ]; then
  lib/gen-ninja | install -DTm 644 /dev/stdin "$datadir/apply.ninja"
fi

# summon ninja
exec ninja -f "$datadir/apply.ninja"
