#!/bin/sh
# apply changes

set -e

sym() { ~/.local/corecon/lib/sym "$1" "$2"; }
sym_corecon() { ~/.local/corecon/lib/sym ~/.local/corecon/"$1" "$2"; }

datadir="${XDG_DATA_HOME:-$HOME/.local/share}/corecon"

# symlink dotfiles
sym_corecon bash/login ~/.bash_profile
sym_corecon bash/bashrc ~/.bashrc
sym_corecon bash/inputrc ~/.inputrc
sym_corecon vim/vimrc ~/.vimrc
sym_corecon lib/dialogrc ~/.dialogrc
sym_corecon lib/screenrc ~/.screenrc

# symlink executables
cd ~/.local/corecon/bin
for bin in *; do
  sym_corecon bin/"$bin" ~/.local/bin/"$bin"
done

exec corecon build
