#!/bin/sh
# ninja configurator

shellquote() {
  if [ "$#" -gt 0 ]; then
    # each argument is fed as a line into sed
    # escape inner quotes
    # prepend and append quotes to each line
    # join arguments with spaces
    printf '%s\n' "$@" | sed "s/'/'\\\\''/g; s/^/'/; s/$/'/" | tr '\n' ' '
  fi
}

ninjaquote() {
  # replace '$' with '$$'
  # replace leading space with '$ '
  printf '%s\n' "$1" | sed 's/\$/$$/g; s/^ /$ /'
}

ninjaquote_path() {
  # escape all '$', ':', and space
  printf '%s\n' "$1" | sed 's/[\$: ]/$\&/g'
}

confdir="${XDG_CONFIG_HOME:-$HOME/.config}/corecon"
datadir="${XDG_DATA_HOME:-$HOME/.local/share}/corecon"

cat <<EOF
builddir = $(ninjaquote "$datadir")

install_mode = 644

rule script
  command = \$in

rule script_output
  command = \$in | install -DTm \$install_mode /dev/stdin \$out

build \$builddir/apply.ninja: script_output lib/gen-ninja
  description = Configure Ninja
  generator = true
EOF
