#!/bin/sh
# get vim-plug

set -e

printf 'Updating Vim-plug...\n'
mkdir -p "$HOME/.vim/autoload"
curl -Lfo "$HOME/.vim/autoload/plug.vim" \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
