#!/bin/sh
# safe symlinker
#
# sym <target> <path>
#
#   Tries to symlink <path> to <target>, or correct an existing symlink. Fails
#   if <target> exists. This behavior is intended to minimize data loss
#   (symlinks are easier to recover). In addition, parent directories are
#   automatically created.
#

target="$1"
path="$2"

if real_target="$(readlink -- "$path")"; then
  # if the target is a symlink, make it point to the right place
  if [ "$real_target" != "$target" ]; then
    printf >&2 'creating symlink: %s -> %s\n' "$path" "$target"
    rm -f -- "$path" && \
      ln -s -- "$target" "$path"
  fi
elif [ -e "$path" ]; then
  # if the target exists, a conflict has occurred
  printf >&2 'refused to overwrite: %s\n' "$path"
  exit 1
else
  # if the target doesn't exist, create the symlink
  printf >&2 'creating symlink: %s -> %s\n' "$path" "$target"
  mkdir -p -- "$(dirname -- "$path")" && \
    ln -s -- "$target" "$path"
fi
