#!/bin/sh
# nnn wrapper
#
# This file is part of Gale.
#
# Dependencies:
#   nnn
#

NNN_BMS=\;
NNN_PLUG=\;

# bookmark <key> <path>
#
#   Bind a bookmark key.
#
bookmark() {
  while case "$NNN_BMS" in *\;"$1":*) true ;; *) false ;; esac
  do NNN_BMS="${NNN_BMS%%\;"$1":*};${NNN_BMS#*\;"$1":*\;}"
  done
  NNN_BMS="$NNN_BMS$1:$2;"
}

# plugin <key> <path>
#
#   Bind a plugin key.
#
plugin() {
  while case "$NNN_PLUG" in *\;"$1":*) true ;; *) false ;; esac
  do NNN_PLUG="${NNN_PLUG%%\;"$1":*};${NNN_PLUG#*\;"$1":*\;}"
  done
  NNN_PLUG="$NNN_PLUG$1:$2;"
}

# add bookmarks
bookmark T /tmp
bookmark C ~/.config
bookmark D ~/.data
bookmark S ~/.log
bookmark X ~/.cache
if [ "$XDG_RUNTIME_DIR" ]; then
  bookmark R "$XDG_RUNTIME_DIR"
fi
bookmark M "/run/media/$USER"

# add plugins
plugin n newwin
plugin t terminal

# if set, specifies a -T option (sort) for nnn
N3_SORT=v

# -A    disable auto-select on unique filter match
# -d    show details
# -H    show hidden files
# -U    show user/group names in status bar
export NNN_OPTS=AdHU

# source local configuration from ~/.config/gale/n3rc, if available
if [ -s ~/.config/gale/n3rc ]; then
  . ~/.config/gale/n3rc
fi

export NNN_BMS=${NNN_BMS#\;}
export NNN_PLUG=${NNN_PLUG#\;}

exec nnn ${N3_SORT:+-T "$N3_SORT"} "$@"
