music_directory "~/music"
db_file "~/.cache/mpd/database"
playlist_directory "~/.data/mpd/playlists"
state_file "~/.data/mpd/state"
restore_paused "yes"
bind_to_address "$XDG_RUNTIME_DIR/mpd/socket"

audio_output {
  type "pipewire"
  name "PipeWire"
}
