#!/usr/bin/env bash
# generate the manifest read by galupd
#
# galupd will invoke ninja in the home directory, so all commands below will
# inherit the the home directory as their initial working directory.
#

shopt -s nullglob
cd "$HOME" || exit 1

echo() { printf '%s\n' "$1"; }
diag() { printf >&2 '%s\n' "$1"; }
warn() { printf >&2 'warning: %s\n' "$1"; }
err() { printf >&2 'error: %s\n' "$1"; }

if [[ ! -d .gale ]]; then
  err "$HOME/.gale isn't a directory!"
  diag "Make sure the Gale repository is mounted there."
  exit 1
fi

ninja_quotep()
{
  printf -v "$1" %s "${!1//\$/\$\$}"
  printf -v "$1" %s "${!1//:/\$:}"
  printf -v "$1" %s "${!1// /\$ }"
}

shell_quotep()
{
  if [[ ${!1} = *[!0-9A-Za-z,./:+=_-]* ]]; then
    printf -v "$1" %s "'${!1//\'/\'\\\'\'}'"
  fi
  printf -v "$1" %s "${!1//\$/\$\$}"
}

# add_install <target> <source> [<mode>]
#
#   Install <source> at <target> (with mode <mode> or 644).
#
add_install()
{
  local target="$1" source="$2" mode="${3-644}"
  ninja_quotep target
  ninja_quotep source
  shell_quotep mode
  echo
  echo "build $target: install $source"
  echo "  mode = $mode"
}

# add_symlink <target> <content>
#
#   Create a symlink <target> pointing to <content>.
#
add_symlink()
{
  local target="$1" content="$2"
  ninja_quotep target
  shell_quotep content
  echo
  echo "build $target: symlink"
  echo "  content = $content"
}

# add_sed <target> <source> <script> [<mode>]
#
#   Install the result of applying the sed script <script> to <source> at
#   <target> (with mode <mode> or 644).
#
add_sed()
{
  local target="$1" source="$2" script="$3" mode="${4-644}"
  ninja_quotep target
  ninja_quotep source
  shell_quotep script
  shell_quotep mode
  echo
  echo "build $target: sed $source"
  echo "  script = $script"
  echo "  mode = $mode"
}

gale_version=$(git -C .gale describe --always --dirty 2>/dev/null) \
  || gale_version=unknown

diag "Gale version $gale_version"
diag "Generating manifest..."

enable_systemd=$(galconf --get --default=no systemd)
diag "  systemd: $enable_systemd"
enable_wayland=$(galconf --get --default=no wayland)
diag "  wayland: $enable_wayland"
enable_sway=$(galconf --get --default=no sway)
diag "  sway: $enable_sway"
enable_hyprland=$(galconf --get --default=no hyprland)
diag "  hyprland: $enable_hyprland"
enable_vim_plug=$(galconf --get --default=yes vim-plug)
diag "  vim-plug: $enable_vim_plug"

cat << ENDOFFILE
# Gale version $gale_version
# $(date)

builddir = .data/gale

rule install
  description = Installing: \$out
  command = install -m \$mode -T \$in \$out

rule symlink
  description = Symlinking: \$out
  command = ln -sf -T \$content \$out

rule sed
  description = Configuring: \$out
  command = sed \$script \$in | install -m \$mode -T /dev/stdin \$out

rule create
  description = Creating: \$out
  command = : > \$out
  generator = 1

rule configure
  description = Regenerating manifest...
  command = .gale/bin/galreconf --auto
  generator = 1
build .data/gale/upd.ninja: configure | .gale/internal/generate-manifest .config/gale/config
build .config/gale/config: create
ENDOFFILE

add_symlink .bashrc .gale/bash/init
add_symlink .bash_profile .gale/bash/profile
add_symlink .vimrc .gale/vim/init.vim
add_symlink .inputrc .gale/core/inputrc
add_symlink .dialogrc .gale/core/dialogrc
add_symlink .screenrc .gale/core/screenrc
add_symlink .lesskey .gale/core/lesskey

for bin in .gale/bin/*; do
  if [ -f "$bin" ] && [ -x "$bin" ]; then
    binname=${bin##*/}
    add_symlink ".local/bin/$binname" "../../$bin"
  fi
done

add_symlink .local/bin/n3 ../../.gale/nnn/n3
add_symlink .local/bin/tn3 ../../.gale/nnn/tn3
add_symlink .data/applications/tn3.desktop ../../.gale/nnn/tn3.desktop

for plugin in .gale/nnn/plugins/*; do
  if [ -f "$plugin" ]; then
    pluginname=${plugin##*/}
    add_symlink ".config/nnn/plugins/$pluginname" "../../../$plugin"
  fi
done

cat << ENDOFFILE
rule get-vim-plug
  description = Downloading vim-plug...
  command = .gale/bin/get-vim-plug
  generator = 1
build .vim/autoload/plug.vim: get-vim-plug
ENDOFFILE

if [ "$enable_systemd" = yes ]; then
  :
fi

if [ "$enable_wayland" = yes ]; then
  add_symlink .config/foot/foot.ini ../../.gale/foot/foot.ini
  add_symlink .config/alacritty/alacritty.yml ../../.gale/alacritty/alacritty.yml
  add_symlink .local/bin/wautosleep ../../.gale/wayland/wautosleep
fi

if [ "$enable_sway" = yes ]; then
  add_symlink .local/bin/gale-sway ../../.gale/sway/gale-sway
  add_symlink .config/sway/config ../../.gale/sway/sway.conf
  add_symlink .local/bin/swaystatus ../../.gale/sway/swaystatus
  add_symlink .local/bin/sway-output-mode ../../.gale/sway/sway-output-mode
fi

if [ "$enable_hyprland" = yes ]; then
  add_symlink .local/bin/galhyprland ../../.gale/hypr/galhyprland
  add_symlink .config/hypr/hyprland.conf ../../.gale/hypr/hyprland.conf
fi
